baseurl = "https://younos.me/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
locale = "en-us"
languageCode = "en-us"
copyright = "2026 Younos Hashem"
theme = "hugo-classic"
title = "Younos Hashem"

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)']]
        [markup.goldmark.renderer]
            unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4




[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 10
[[menu.main]]
name = "End Malaria"
url = "/malaria/"
weight = 20
[[menu.feed]]
name = "CV"
url = "/files/yhashem_cv.pdf"

[params]
  custom_css = ["css/theme-override.css"]
  description = "A simple, minimal blog for those who love text."
  footer = """\
  [Github](https://github.com/younos-hashem) \
  | [LinkedIn](https://linkedin.com/in/younos-hashem) \
  | [Google Scholar](https://scholar.google.com/citations?user=wh8WbvMAAAAJ&hl=en&oi=ao) \
  | [About the site](/about/)"""
  [params.author]
    email = "younos.hashem@stonybrook.edu"
    name = "Younos Hashem"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputs]
home = ["html", "rss"]
section = ["html", "rss"]
taxonomy = ["html"]
term = ["html"]